### ISSUE TITLE
About error of aim 

### ISSUE THREAD

**Issue by chenqs1995** [xiaoye-hhh/SAAI#5]
I encountered the following error during operation, how to solve it?

Epoch[1] Complete. Time taken: 00:01:00
Engine run complete. Time taken 00:01:00
Engine run is terminating due to exception: 'Engine' object has no attribute 'aim'
Traceback (most recent call last):
  File "/home/T3090U2/project/CQS/code/infrared/SAAI/train.py", line 219, in <module>
    train(cfg)
  File "/home/T3090U2/project/CQS/code/infrared/SAAI/train.py", line 153, in train
    engine.run(train_loader, max_epochs=cfg.num_epoch)
  File "/home/T3090U2/anaconda3/envs/saai/lib/python3.10/site-packages/ignite/engine/engine.py", line 326, in run
    self._handle_exception(e)
  File "/home/T3090U2/anaconda3/envs/saai/lib/python3.10/site-packages/ignite/engine/engine.py", line 291, in _handle_exception
    raise e
  File "/home/T3090U2/anaconda3/envs/saai/lib/python3.10/site-packages/ignite/engine/engine.py", line 317, in run
    self._fire_event(Events.EPOCH_COMPLETED)
  File "/home/T3090U2/anaconda3/envs/saai/lib/python3.10/site-packages/ignite/engine/engine.py", line 226, in _fire_event
    func(self, *(event_args + args), **kwargs)
  File "/home/T3090U2/project/CQS/code/infrared/SAAI/engine/__init__.py", line 150, in epoch_completed_callback
    mAP, r1, r5, _, _ = eval_sysu(q_feats, q_ids, q_cams, g_feats, g_ids, g_cams, g_img_paths, perm, mode='all', num_shots=1, aim=engine.aim)
AttributeError: 'Engine' object has no attribute 'aim'

**Comment by xiaoye-hhh** [comment]
You can simply specify it as True.

**Comment by xiaoye-hhh** [comment]
You can change as: 
`mAP, r1, r5, _, _ = eval_sysu(q_feats, q_ids, q_cams, g_feats, g_ids, g_cams, g_img_paths, perm, mode='all', num_shots=1, aim=False)`

**Comment by yuting-coder** [comment]
> You can change as: `mAP, r1, r5, _, _ = eval_sysu(q_feats, q_ids, q_cams, g_feats, g_ids, g_cams, g_img_paths, perm, mode='all', num_shots=1, aim=False)`

I encountered the following error during change this operation, how to solve it?

Epoch[1] Complete. Time taken: 00:01:00
Engine run complete. Time taken 00:01:11
Engine run is terminating due to exception: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous
Traceback (most recent call last):
  File "D:\anaconda\envs\cumtlh\lib\site-packages\ignite\engine\engine.py", line 326, in run
    self._handle_exception(e)
  File "D:\anaconda\envs\cumtlh\lib\site-packages\ignite\engine\engine.py", line 291, in _handle_exception
    raise e
  File "D:\anaconda\envs\cumtlh\lib\site-packages\ignite\engine\engine.py", line 317, in run
    self._fire_event(Events.EPOCH_COMPLETED)
  File "D:\anaconda\envs\cumtlh\lib\site-packages\ignite\engine\engine.py", line 226, in _fire_event
    func(self, *(event_args + args), **kwargs)
  File "F:\paper_code_YT\2024\01\SFE\engine\__init__.py", line 150, in epoch_completed_callback
    mAP, r1, r5, _, _ = eval_sysu(q_feats, q_ids, q_cams, g_feats, g_ids, g_cams, g_img_paths, perm, mode='all', num_shots=1, aim=False)
  File "F:\paper_code_YT\2024\01\SFE\utils\eval_sysu.py", line 133, in eval_sysu
    dist_mat = pairwise_distance(query_feats, g_feat)
  File "F:\paper_code_YT\2024\01\SFE\utils\eval_sysu.py", line 15, in pairwise_distance
    y = y.view(n, -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous
python-BaseException

Process finished with exit code 1
